apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: apod

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml

commonLabels:
  app.kubernetes.io/managed-by: argocd

images:
  - name: REGION-docker.pkg.dev/GCP_PROJECT_ID/apod-explorer/apod-next
    # Argo CD Image Updater or your CI pipeline updates this tag:
    newTag: latest
