apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: apod

resources:
- namespace.yaml
- deployment.yaml
- service.yaml

commonLabels:
  app.kubernetes.io/managed-by: argocd

    # Argo CD Image Updater or your CI pipeline updates this tag:
images:
- name: REGION-docker.pkg.dev/GCP_PROJECT_ID/apod-explorer/apod-next
  newTag: latest
- name: europe-west1-docker.pkg.dev/project-8941b0d3-e922-4da2-a3c/apod-explorer/apod-next
  newTag: "31"
