apiVersion: v1
kind: Service
metadata:
  name: apod
  namespace: apod
  labels:
    app.kubernetes.io/name: apod
    app.kubernetes.io/component: web
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: apod
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
